name: Docker Image CI

on:
#   schedule:
#     - cron:  '0 */5 * * *'
   workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: nextcloud:stable
          image: sldaniel/nextcloud-ffmpeg:stable
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.check.outputs.needs-updating == 'true'
  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:nextcloud-ffmpeg"
          push: true
          tags: sldaniel/nextcloud-ffmpeg:stable
        if: steps.check.outputs.needs-updating == 'true'
