# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  exec:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Manual Trigger
      # You may pin to the exact commit or the version.
      # uses: benhamiltonpro/manual-trigger@17718624ddb91f8e75274b3f7bb45c9f2071d173
      uses: benhamiltonpro/manual-trigger@v1.0.2
      with:
        # Run name that you can use for your workflow if triggers
        RUN_NAME: Docker Image CI
